version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entering pre build stage
      - pwd
      - ls -ltr
      - df -h
      - pip install awscli --upgrade --user
  build:
    commands:
      - echo Entered the build phase...
      - DT=`date +%Y-%m-%d-%S`
      - echo $DT
      - echo $DBucketenv
      - printf '{\n "epoctime":"%s",\n' $DT > build.json
      - printf '"DBucket":"%s" \n}' $DBucketenv >> build.json
      - cat build.json
      - ls -ltr
      - aws s3 cp --recursive ./nested s3://$DBucketenv/$DT/
      - StackStatus=`aws cloudformation describe-stacks --stack-name $StackName --query Stacks[].StackStatus --output text`
      - echo $StackStatus
      - if [ $StackStatus == 'ROLLBACK_COMPLETE' ]; then echo "This stack previous status was in ROLLBACK_COMPLETE state, so cleaning up this stack"; aws cloudformation delete-stack --stack-name $StackName; else echo "Continue for next stage"; fi
    finally:
      - echo This always runs even if build command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files: build.json
